bashCmd-Mer 30 mai 2018 01:05:43 CEST

diff --git a/bashCmd/Makefile b/bashCmd/Makefile
--- a/bashCmd/Makefile
+++ b/bashCmd/Makefile
@@ -9,17 +9,47 @@ getP=
 home ?= /home/mlds/
 home_custom ?= .custom
 home_work ?= work
-
+k := $(strip $(PWD))
+j = $(shell [[ -z "${custom}" ]] || echo "-v \"${custom}:${home}${home_custom}\"")
+jj = $(shell [[ -z "${work}" ]] || echo "-v \"$(k)/$(work):${home}${home_work}\"")
 
 portNb ?= 8888
 portTensorBoard ?= 6006
 portH2o ?= 54321
-portSpark ?= 4004
+portSpark ?= 7077
+
+portSparkMaster ?= 8080
+portSparkMasterMin ?= 8080
+portSparkMasterNb ?= 10
+portSparkMasterMax ?= $$((${portSparkMasterMin} + ${portSparkMasterNb}))
+
+portSparkSlave ?= 8081
+portSparkSlaveMin ?= 8081
+portSparkSlaveNb ?= 10
+portSparkSlaveMax ?= $$((${portSparkSlaveMin} + ${portSparkSlaveNb}))
+
+portSparkRest ?= 6066
+portSparkRestMin ?= 6066
+portSparkRestNb ?= 10
+portSparkRestMax ?= $$((${portSparkRestMin} + ${portSparkRestNb}))
+
+
+portSparkContextB ?= 4040
+portSparkContextBMin ?= 4040
+portSparkContextBNb ?= 100
+portSparkContextBMax ?= $$((${portSparkContextBMin} + ${portSparkContextBNb}))
+
+portSparkContextE ?= 4050
+portSparkContextEMin ?= 4050
+portSparkContextENb ?= 100
+portSparkContextEMax ?= $$((${portSparkContextEMin} + ${portSparkContextENb}))
+
+
 
 portNbMin ?= 8888
 portTensorBoardMin ?= 6006
 portH2oMin ?= 54321
-portSparkMin ?= 4004
+portSparkMin ?= 7077
 
 portNbNb ?= 10
 portTensorBoardNb ?= 10
@@ -31,14 +61,14 @@ portTensorBoardMax ?= $$((${portTensorBoardMin} + ${portTensorBoardNb}))
 portH2oMax ?= $$((${portH2oMin} + ${portH2oNb}))
 portSparkMax ?= $$((${portSparkMin} + ${portSparkNb}))
 
-more ?= ""
+more ?= 
 debug ?= -d
 run_rm ?= --rm
 printCommand ?= "yes"
 
 
 quiet="no"
-k := $(strip $(PWD))
+
 
 help:
 	@echo "make mlds"
@@ -58,9 +88,15 @@ mlds:
 	fi && a=$$($$getP ${portNbMin} ${portNbMax}  2> /dev/null) && \
 b=$$($$getP ${portTensorBoardMin} ${portTensorBoardMax} 2> /dev/null) && \
 c=$$($$getP ${portH2oMin} ${portH2oMax} 2> /dev/null) && \
-d=$$($$getP ${portSparkMin} ${portSparkMax} 2> /dev/null) && test -z $$getP  && echo "Error ------ getP"  || (\
-	((test ${printCommand} = "yes" && test ${quiet} = "no" ) && echo 'docker run  "${debug}" "${run_rm}"  -v "${custom}:${home}${home_custom}"  -v "$(k)/$(work):${home}${home_work}" -p "'$$( echo $$d)':${portSpark}"  -p "'$$( echo $$a)':${portNb}" -p "'$$( echo $$b)':${portTensorBoard}" -p "'$$( echo $$c)':${portH2o}"  "${image}${latest}" ${cmd}' || true ) && \
-	docker run  --expose="1-10000" "${debug}" "${run_rm}"  -v "${custom}:${home}${home_custom}"  -v "$(k)/$(work):${home}${home_work}" -p "$$d:${portSpark}"  -p "$$a:${portNb}" -p "$$b:${portTensorBoard}" -p "$$c:${portH2o}" ${more} "${image}${latest}"  ${cmd}  || ( echo "Error ---- Help: " && make help ) )
+d=$$($$getP ${portSparkMin} ${portSparkMax} 2> /dev/null) && \
+e=$$($$getP ${portSparkMasterMin} ${portSparkMasterMax} 2> /dev/null) && \
+f=$$(($$e+1)) && \
+g=$$($$getP ${portSparkContextBMin} ${portSparkContextBMax} 2> /dev/null) && \
+h=$$($$getP ${portSparkRestMin} ${portSparkRestMax} 2> /dev/null) && \
+i=$$($$getP ${portSparkContextEMin} ${portSparkContextEMax} 2> /dev/null) && \
+	 test -z $$getP  && echo "Error ------ getP"  || (\
+	((test ${printCommand} = "yes" && test ${quiet} = "no" ) && echo 'docker run  "${debug}" "${run_rm}" ${j} ${jj} -p "'$$( echo $$d)':${portSpark}" -p "'$$( echo $$g)'-'$$( echo $$i)':${portSparkContextB}-${portSparkContextE}" -p "'$$( echo $$h)':${portSparkRest}" -p "'$$( echo $$f)':${portSparkSlave}" -p "'$$( echo $$e)':${portSparkMaster}" -p "'$$( echo $$a)':${portNb}" -p "'$$( echo $$b)':${portTensorBoard}" -p "'$$( echo $$c)':${portH2o}"  "${image}${latest}" ${cmd}' || true ) && \
+	docker run  "${debug}" "${run_rm}"  ${j} ${jj} -p "$$d:${portSpark}" -p "$$g-$$i:${portSparkContextB}-${portSparkContextE}" -p "$$h:${portSparkRest}" -p "$$f:${portSparkSlave}" -p "$$e:${portSparkMaster}" -p "$$a:${portNb}" -p "$$b:${portTensorBoard}" -p "$$c:${portH2o}" ${more} "${image}${latest}"  ${cmd}  || ( echo "Error ---- Help: " && make help ) )
 define PB
 	echo "PB"
 endef	
